-- Presupuesto 2026, volcado desde la hoja Previsión de Presupuesto_2026.xlsx
-- Generado el 2026-08-20.
--
-- CONVENIO DE SIGNOS: el mismo que en movimientos.
--   ingreso                       -> importe positivo
--   gasto / ahorro / inversion    -> importe negativo
-- Sin esto, v_ppto_vs_real restaria un positivo de un negativo y la
-- desviacion saldria del doble del importe.
--
-- Solo se vuelcan los importes distintos de cero.
-- Idempotente: reejecutarlo sobrescribe los importes, no duplica filas.

SET SESSION sql_mode = CONCAT(@@sql_mode, ',STRICT_ALL_TABLES');

INSERT INTO presupuesto (anio, mes, categoria_id, importe) VALUES
  (2026, 1, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 5194.07),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Pagas extraordinarias'), 5194.07),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Pagas extraordinarias'), 5194.07),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), -73.45),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Inversión 4'), -3.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), -195.06),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Seguro Hogar-Hipoteca'), -401.11),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), -80.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Alarma'), -49.8),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Alarma'), -49.8),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (cocina)05/MM'), -1956.53),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (cocina)05/MM'), -1956.53),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (cocina)05/MM'), -1956.53),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (cocina)05/MM'), -1956.53),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), -79.67),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), -30.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), -20.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Gasolina'), -90.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), -10.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), -40.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), -21.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), -41.02),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), -20.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Comida Quillo'), -85.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Comida Quillo'), -85.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Comida Quillo'), -85.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Comida Quillo'), -85.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), -200.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), -20.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), -40.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), -40.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), -57.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), -144.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), -10.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), -1125.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), -40.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), -15.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), -30.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), -19.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Google'), -9.95),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Actividades extraescolares'), -17.51),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), -20.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), -524.28),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), -50.0),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), -40.0),
  (2026, 1, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -9.95),
  (2026, 2, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 3, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 4, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 5, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 6, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 7, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 8, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 9, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 10, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 11, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0),
  (2026, 12, (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), -40.0)
ON DUPLICATE KEY UPDATE importe = VALUES(importe);

-- Comprobacion
SELECT c.tipo,
       COUNT(*)                AS lineas,
       ROUND(SUM(p.importe),2) AS suma_anual
  FROM presupuesto p JOIN categorias c ON c.id = p.categoria_id
 WHERE p.anio = 2026
 GROUP BY c.tipo WITH ROLLUP;