-- Semilla de categorias, generada desde Presupuesto_2026.xlsx
-- Idempotente: se puede reejecutar sin duplicar.

INSERT INTO categorias (categoria, subcategoria, tipo, reparto, orden) VALUES
  ('INGRESOS', 'Sueldo 1', 'ingreso', NULL, 0),
  ('INGRESOS', 'Sueldo 2', 'ingreso', NULL, 10),
  ('INGRESOS', 'Pagas extraordinarias', 'ingreso', NULL, 20),
  ('INGRESOS', 'Intereses', 'ingreso', NULL, 30),
  ('INGRESOS', 'Retorno de negocios', 'ingreso', NULL, 40),
  ('INGRESOS', 'Retorno de inversiones', 'ingreso', NULL, 50),
  ('INGRESOS', 'Alquileres', 'ingreso', NULL, 60),
  ('INGRESOS', 'Royalties', 'ingreso', NULL, 70),
  ('INGRESOS', 'Derechos', 'ingreso', NULL, 80),
  ('INGRESOS', 'Trabajos extra', 'ingreso', NULL, 90),
  ('INGRESOS', 'Licencias y patentes', 'ingreso', NULL, 100),
  ('INGRESOS', 'Otros', 'ingreso', NULL, 110),
  ('AHORRO', 'Colchón de Seguridad', 'ahorro', 'ahorro_inversion', 120),
  ('AHORRO', 'Periodificaciones', 'ahorro', 'ahorro_inversion', 130),
  ('AHORRO', 'Objetivos', 'ahorro', 'ahorro_inversion', 140),
  ('AHORRO', 'Ahorro', 'ahorro', 'ahorro_inversion', 150),
  ('INVERSIÓN', 'Fondos de Inversión', 'inversion', 'ahorro_inversion', 180),
  ('INVERSIÓN', 'Acciones', 'inversion', 'ahorro_inversion', 190),
  ('INVERSIÓN', 'Planes de Pensión', 'inversion', 'ahorro_inversion', 200),
  ('INVERSIÓN', 'Inversión 4', 'inversion', 'ahorro_inversion', 210),
  ('INVERSIÓN', 'Inversión 5', 'inversion', 'ahorro_inversion', 220),
  ('INVERSIÓN', 'Inversión 6', 'inversion', 'ahorro_inversion', 230),
  ('VIVIENDA', 'Alquiler', 'gasto', 'fijo', 240),
  ('VIVIENDA', 'Hipoteca', 'gasto', 'fijo', 250),
  ('VIVIENDA', 'IBI', 'gasto', 'fijo', 260),
  ('VIVIENDA', 'Seguro Hogar-Hipoteca', 'gasto', 'fijo', 270),
  ('VIVIENDA', 'Seguro Vida-Hipoteca', 'gasto', 'fijo', 280),
  ('VIVIENDA', 'Comunidad', 'gasto', 'fijo', 290),
  ('VIVIENDA', 'Reparaciones', 'gasto', 'fijo', 300),
  ('VIVIENDA', 'Alarma', 'gasto', 'fijo', 310),
  ('VIVIENDA', 'Equipamiento (cocina)05/MM', 'gasto', 'fijo', 320),
  ('VIVIENDA', 'Equipamiento (sofá)05/MM', 'gasto', 'fijo', 330),
  ('VIVIENDA', 'Ayuda doméstica', 'gasto', 'fijo', 340),
  ('VIVIENDA', 'Otros', 'gasto', 'fijo', 350),
  ('ALIMENTACIÓN', 'Frutería', 'gasto', 'fijo', 360),
  ('ALIMENTACIÓN', 'Carnicería', 'gasto', 'fijo', 370),
  ('ALIMENTACIÓN', 'Pescadería', 'gasto', 'fijo', 380),
  ('ALIMENTACIÓN', 'Limpieza', 'gasto', 'fijo', 390),
  ('ALIMENTACIÓN', 'General', 'gasto', 'fijo', 400),
  ('ALIMENTACIÓN', 'Desayunos/meriendas', 'gasto', 'fijo', 410),
  ('TRANSPORTE', 'Furgoneta', 'gasto', 'fijo', 420),
  ('TRANSPORTE', 'Vehículo 2', 'gasto', 'fijo', 430),
  ('TRANSPORTE', 'Gasolina', 'gasto', 'variable', 440),
  ('TRANSPORTE', 'Seguro Vehículo 1', 'gasto', 'fijo', 450),
  ('TRANSPORTE', 'Seguro Vehículo 2', 'gasto', 'fijo', 460),
  ('TRANSPORTE', 'ITV', 'gasto', 'fijo', 470),
  ('TRANSPORTE', 'Impuesto circulación', 'gasto', 'fijo', 480),
  ('TRANSPORTE', 'Revisiones y mantenimiento', 'gasto', 'fijo', 490),
  ('TRANSPORTE', 'Equipamiento', 'gasto', 'fijo', 500),
  ('TRANSPORTE', 'Garaje', 'gasto', 'fijo', 510),
  ('TRANSPORTE', 'Peajes, aparcamientos', 'gasto', 'fijo', 520),
  ('TRANSPORTE', 'Lavado', 'gasto', 'fijo', 530),
  ('TRANSPORTE', 'Multas', 'gasto', 'fijo', 540),
  ('TRANSPORTE', 'Transporte publico', 'gasto', 'variable', 550),
  ('TRANSPORTE', 'Taxis', 'gasto', 'variable', 560),
  ('TRANSPORTE', 'Otros', 'gasto', 'fijo', 570),
  ('SERVICIOS', 'Electricidad', 'gasto', 'fijo', 580),
  ('SERVICIOS', 'Agua', 'gasto', 'fijo', 590),
  ('SERVICIOS', 'Gas', 'gasto', 'fijo', 600),
  ('SERVICIOS', 'Teléfono/Móvil/Internet', 'gasto', 'fijo', 610),
  ('SERVICIOS', 'Limpieza', 'gasto', 'fijo', 620),
  ('SERVICIOS', 'Honorarios', 'gasto', 'fijo', 630),
  ('SERVICIOS', 'Seguro de Vida', 'gasto', 'fijo', 640),
  ('SERVICIOS', 'Seguro Decesos', 'gasto', 'fijo', 650),
  ('SERVICIOS', 'Seguro de crédito', 'gasto', 'fijo', 660),
  ('SERVICIOS', 'Seguro de Responsabilidad Civil', 'gasto', 'fijo', 670),
  ('SERVICIOS', 'Seguro por Incapacidad', 'gasto', 'fijo', 680),
  ('SERVICIOS', 'Alarma', 'gasto', 'fijo', 690),
  ('SERVICIOS', 'Gestor', 'gasto', 'fijo', 700),
  ('SERVICIOS', 'Comisiones', 'gasto', 'variable', 710),
  ('SERVICIOS', 'Intereses', 'gasto', 'variable', 720),
  ('SERVICIOS', 'Canguros', 'gasto', 'fijo', 730),
  ('SERVICIOS', 'Otros', 'gasto', 'fijo', 740),
  ('IMPUESTOS', 'IRPF', 'gasto', 'variable', 750),
  ('IMPUESTOS', 'IVA (trimestrales)', 'gasto', 'fijo', 760),
  ('IMPUESTOS', 'ITP', 'gasto', 'fijo', 770),
  ('IMPUESTOS', 'ISD', 'gasto', 'fijo', 780),
  ('IMPUESTOS', 'Tasas', 'gasto', 'fijo', 790),
  ('IMPUESTOS', 'Recibo Autónomos', 'gasto', 'fijo', 800),
  ('IMPUESTOS', 'Otros', 'gasto', 'fijo', 810),
  ('PERSONALES', 'Belleza', 'gasto', 'variable', 820),
  ('PERSONALES', 'Ropa', 'gasto', 'variable', 830),
  ('PERSONALES', 'Colecciones', 'gasto', 'variable', 840),
  ('PERSONALES', 'Comida Quillo', 'gasto', 'fijo', 850),
  ('PERSONALES', 'Tarjeta de Crédito', 'gasto', 'variable', 860),
  ('PERSONALES', 'Peluquería Quillo', 'gasto', 'variable', 870),
  ('PERSONALES', 'Vicios', 'gasto', 'variable', 880),
  ('PERSONALES', 'Compras', 'gasto', 'variable', 890),
  ('PERSONALES', 'Lotería', 'gasto', 'variable', 900),
  ('PERSONALES', 'Cosas para la casa', 'gasto', 'variable', 910),
  ('SALUD', 'Seguro médico', 'gasto', 'fijo', 920),
  ('SALUD', 'Seguro Accidentes', 'gasto', 'variable', 930),
  ('SALUD', 'Tratamientos', 'gasto', 'variable', 940),
  ('SALUD', 'Suplementos', 'gasto', 'variable', 950),
  ('SALUD', 'Gimnasio- deportes', 'gasto', 'fijo', 960),
  ('SALUD', 'Farmacia', 'gasto', 'variable', 970),
  ('SALUD', 'Rehabilitación', 'gasto', 'fijo', 980),
  ('OCIO', 'Vacaciones', 'gasto', 'variable', 990),
  ('OCIO', 'Viajes', 'gasto', 'variable', 1000),
  ('OCIO', 'Escapadas', 'gasto', 'variable', 1010),
  ('OCIO', 'Cines, teatros, espectáculos', 'gasto', 'variable', 1020),
  ('OCIO', 'Bares, restaurantes', 'gasto', 'variable', 1030),
  ('OCIO', 'Take-away', 'gasto', 'variable', 1040),
  ('OCIO', 'Suscripciones', 'gasto', 'variable', 1050),
  ('OCIO', 'membresías', 'gasto', 'variable', 1060),
  ('OCIO', 'Google', 'gasto', 'variable', 1070),
  ('NIÑAS', 'Guardería', 'gasto', 'fijo', 1080),
  ('NIÑAS', 'Actividades extraescolares', 'gasto', 'fijo', 1090),
  ('NIÑAS', 'ocio', 'gasto', 'variable', 1100),
  ('NIÑAS', 'Ropa', 'gasto', 'variable', 1110),
  ('NIÑAS', 'Material Escolar', 'gasto', 'fijo', 1120),
  ('NIÑAS', 'Pensión Alimenticia', 'gasto', 'fijo', 1130),
  ('TECNOLOGÍA', 'Servidores', 'gasto', 'variable', 1140),
  ('TECNOLOGÍA', 'Reserwa', 'gasto', 'variable', 1150),
  ('TECNOLOGÍA', 'IA', 'gasto', 'variable', 1160),
  ('TECNOLOGÍA', 'Formación', 'gasto', 'variable', 1170),
  ('TECNOLOGÍA', 'Hardware', 'gasto', 'variable', 1180),
  ('TECNOLOGÍA', 'Google', 'gasto', 'variable', 1190),
  ('TRASPASOS', 'Entre cuentas propias', 'traspaso', NULL, 1200),
  ('TRASPASOS', 'PayPal financiación', 'traspaso', NULL, 1210),
  ('VIVIENDA', 'Obra', 'gasto', 'variable', 1220),
  ('TECNOLOGÍA', 'Metales', 'inversion', 'ahorro_inversion', 1230),
  ('PERSONALES', 'Efectivo', 'gasto', 'variable', 1240),
  ('PERSONALES', 'Bizum personas', 'gasto', 'variable', 1250),
  ('PERSONALES', 'Varios', 'gasto', 'variable', 1260)
ON DUPLICATE KEY UPDATE tipo=VALUES(tipo), reparto=VALUES(reparto);

-- ---------------------------------------------------------------------
-- Aborta si alguna regla apunta a una categoria que no existe, en vez de
-- fallar con "columna categoria_id no puede ser nula".
-- ---------------------------------------------------------------------
SET SESSION sql_mode = CONCAT(@@sql_mode, ',STRICT_ALL_TABLES');

-- Reglas de clasificacion. prioridad menor = se evalua antes.
INSERT INTO reglas (patron, tipo_patron, categoria_id, origen, prioridad, excluir) VALUES
  ('cash fresh', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('mercadona', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('aldi', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('lidl', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('carrefour', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('ok markt', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('perfumeria prim', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('papeleria is go', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('herbodietetica', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('biotienda', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('selecto', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('supeco', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='General'), 'todos', 10, 0),
  ('rafael ruiz bar', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), 'todos', 10, 0),
  ('crustum panem', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), 'todos', 10, 0),
  ('gallito', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), 'todos', 10, 0),
  ('desavio la more', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), 'todos', 10, 0),
  ('vending colon', 'contiene', (SELECT id FROM categorias WHERE categoria='ALIMENTACIÓN' AND subcategoria='Desayunos/meriendas'), 'todos', 10, 0),
  ('uber *eats', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), 'todos', 10, 0),
  ('glovo', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), 'todos', 10, 0),
  ('breadsquare', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), 'todos', 10, 0),
  ('burger king', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), 'todos', 10, 0),
  ('telepizza', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Take-away'), 'todos', 10, 0),
  ('bar rudy', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('bar la piscina', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('patio triana', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('cafeteria sanmi', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('el cafe del tre', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('sal gorda', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('tabanco la mita', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('gloria bendita', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('san juan alfara', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('baobab', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('food studio', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Bares, restaurantes'), 'todos', 10, 0),
  ('farmacia', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Farmacia'), 'todos', 10, 0),
  ('clinica aljamar', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Tratamientos'), 'todos', 10, 0),
  ('interhanse', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Seguro médico'), 'todos', 10, 0),
  ('centro de rehabilita', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Rehabilitación'), 'todos', 10, 0),
  ('zonafit', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), 'todos', 10, 0),
  ('go fit', 'contiene', (SELECT id FROM categorias WHERE categoria='SALUD' AND subcategoria='Gimnasio- deportes'), 'todos', 10, 0),
  ('uber *trip', 'contiene', (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), 'todos', 10, 0),
  ('ubr* pending', 'contiene', (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), 'todos', 10, 0),
  ('cabify', 'contiene', (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), 'todos', 10, 0),
  ('taxi', 'contiene', (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Taxis'), 'todos', 20, 0),
  ('renfe', 'contiene', (SELECT id FROM categorias WHERE categoria='TRANSPORTE' AND subcategoria='Transporte publico'), 'todos', 10, 0),
  ('xfera moviles', 'contiene', (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), 'todos', 10, 0),
  ('digi spain', 'contiene', (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Teléfono/Móvil/Internet'), 'todos', 10, 0),
  ('energia xxi', 'contiene', (SELECT id FROM categorias WHERE categoria='SERVICIOS' AND subcategoria='Electricidad'), 'todos', 10, 0),
  ('securitas direct', 'contiene', (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Alarma'), 'todos', 10, 0),
  ('comunidad calle', 'contiene', (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Comunidad'), 'todos', 10, 0),
  ('liquidacion periodica prestamo', 'contiene', (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Hipoteca'), 'todos', 10, 0),
  ('banco cetelem', 'contiene', (SELECT id FROM categorias WHERE categoria='VIVIENDA' AND subcategoria='Equipamiento (sofá)05/MM'), 'todos', 10, 0),
  ('leroy merlin', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Cosas para la casa'), 'todos', 10, 0),
  ('ikea', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Cosas para la casa'), 'todos', 10, 0),
  ('openai', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('claude.ai', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('cursor', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('elevenlabs', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('windsurf', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('anthropic', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='IA'), 'todos', 10, 0),
  ('hetzner', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), 'todos', 10, 0),
  ('contabo', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), 'todos', 10, 0),
  ('dondominio', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), 'todos', 10, 0),
  ('ionos', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Servidores'), 'todos', 10, 0),
  ('google*google', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), 'todos', 10, 0),
  ('apple.com/bill', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Google'), 'todos', 10, 0),
  ('patrimonio metales', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Metales'), 'todos', 5, 0),
  ('silver & gold', 'contiene', (SELECT id FROM categorias WHERE categoria='TECNOLOGÍA' AND subcategoria='Metales'), 'todos', 5, 0),
  ('nudista investor', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='membresías'), 'todos', 10, 0),
  ('hiveagile', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='membresías'), 'todos', 10, 0),
  ('danielprimo', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='membresías'), 'todos', 10, 0),
  ('sharingful', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('podimo', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('movistar plus', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('selectavision', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('netflix', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('spotify', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Suscripciones'), 'todos', 10, 0),
  ('sala cero', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), 'todos', 10, 0),
  ('la mascara prod', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), 'todos', 10, 0),
  ('cartuja center', 'contiene', (SELECT id FROM categorias WHERE categoria='OCIO' AND subcategoria='Cines, teatros, espectáculos'), 'todos', 10, 0),
  ('nyx*goplayocio', 'contiene', (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), 'todos', 10, 0),
  ('canguro aventur', 'contiene', (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), 'todos', 10, 0),
  ('estanco', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Vicios'), 'todos', 10, 0),
  ('clinica veterin', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), 'todos', 10, 0),
  ('las barberas', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Peluquería Quillo'), 'todos', 10, 0),
  ('decathlon', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), 'todos', 10, 0),
  ('dedoles', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), 'todos', 10, 0),
  ('zara', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), 'todos', 10, 0),
  ('lefties', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Ropa'), 'todos', 10, 0),
  ('amzn mktp', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), 'todos', 20, 0),
  ('amazon', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), 'todos', 20, 0),
  ('el corte ingles', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), 'todos', 20, 0),
  ('aliexpress', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Compras'), 'todos', 20, 0),
  ('juguetilandia', 'contiene', (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='ocio'), 'todos', 10, 0),
  ('favor de elena', 'contiene', (SELECT id FROM categorias WHERE categoria='NIÑAS' AND subcategoria='Pensión Alimenticia'), 'todos', 10, 0),
  ('ayuntamiento', 'contiene', (SELECT id FROM categorias WHERE categoria='IMPUESTOS' AND subcategoria='Tasas'), 'todos', 10, 0),
  ('wizink', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), 'todos', 10, 0),
  ('financiera el corte ingles', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Tarjeta de Crédito'), 'todos', 5, 0),
  ('allianz pensiones', 'contiene', (SELECT id FROM categorias WHERE categoria='INVERSIÓN' AND subcategoria='Planes de Pensión'), 'todos', 10, 0),
  ('pension de tesoreria', 'contiene', (SELECT id FROM categorias WHERE categoria='INGRESOS' AND subcategoria='Sueldo 1'), 'todos', 10, 0),
  ('retirada de efectivo', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Efectivo'), 'todos', 10, 0),
  ('bizum', 'contiene', (SELECT id FROM categorias WHERE categoria='PERSONALES' AND subcategoria='Bizum personas'), 'todos', 50, 0),
  ('paypal', 'contiene', (SELECT id FROM categorias WHERE categoria='TRASPASOS' AND subcategoria='PayPal financiación'), 'banco', 1, 1),
  ('barrero martinez carlos', 'contiene', (SELECT id FROM categorias WHERE categoria='TRASPASOS' AND subcategoria='Entre cuentas propias'), 'todos', 1, 1),
  ('carlos barrero ma', 'contiene', (SELECT id FROM categorias WHERE categoria='TRASPASOS' AND subcategoria='Entre cuentas propias'), 'todos', 1, 1)
ON DUPLICATE KEY UPDATE categoria_id=VALUES(categoria_id), prioridad=VALUES(prioridad), excluir=VALUES(excluir);
